-- ==============================================================================
-- Live Q&A Database Schema: Threaded Replies Table
-- Run this in your Supabase SQL Editor (Dashboard -> SQL Editor -> New Query)
-- ==============================================================================

-- 1. Create replies table to store follow-up comments and speaker answers
CREATE TABLE IF NOT EXISTS public.replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    author TEXT DEFAULT 'Attendee',
    is_speaker BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Realtime updates for replies
-- (Note: 'questions' is already part of supabase_realtime, so only 'replies' needs to be added)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' 
        AND schemaname = 'public' 
        AND tablename = 'replies'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.replies;
    END IF;
END $$;

-- 3. Grant table & sequence permissions to anon / authenticated roles
GRANT ALL ON TABLE public.replies TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.replies_id_seq TO anon, authenticated, service_role;
